/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ConeccionBD;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author peyu
 */
public class PruebaDB extends javax.swing.JFrame implements controlador.DBSentencias {

    private String query = controlador.DBSentencias.listaRes;

    public PruebaDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxListas = new javax.swing.JComboBox();
        BtnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMuestra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboxListas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Listar Reservas", "Listar Huespedes" }));
        cboxListas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxListasItemStateChanged(evt);
            }
        });
        cboxListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxListasActionPerformed(evt);
            }
        });

        BtnConsultar.setText("Consultar");
        BtnConsultar.setToolTipText("");
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });

        tableMuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMuestra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnConsultar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConsultar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        // TODO add your handling code here:
        int filas = 0;

        try {

            ResultSetMetaData metaDatos = null;
            int cantiCol = 0;

            ConeccionBD cone = new ConeccionBD();
            Statement sentencia = cone.conectar.createStatement();
            ResultSet rs = sentencia.executeQuery(query);

            DefaultTableModel modelo = new DefaultTableModel();

            modelo = ConeccionBD.ResSet2DTM(rs); //recibe un resultset y dvuelve un DefaultTableModel configurado

            tableMuestra.setModel(modelo);

            metaDatos = rs.getMetaData();  // Consigo los metadatos
            cantiCol = metaDatos.getColumnCount();    // Consigo la cantidad de columnas                     

            while (rs.next()) {
                // Se crea un array que será una de las filas de la tabla.
                Object[] nuevaFila = new Object[cantiCol]; // Hay cuatro columnas en la tabla

                // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
                for (int i = 0; i < cantiCol; i++) {
                    nuevaFila[i] = rs.getObject(i + 1); // El primer indice en rs es el 1, no el cero, por eso se suma 1.

                }

                // Se añade al modelo la fila completa.
                modelo.addRow(nuevaFila);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void cboxListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxListasActionPerformed

    private void cboxListasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxListasItemStateChanged
        // TODO add your handling code here:
        if (evt.getSource() == cboxListas) {
            String seleccionado = (String) cboxListas.getSelectedItem();

            if (seleccionado == "Listar Reservas") {
                query = null;
                query = controlador.DBSentencias.listaRes;
                //System.out.println(query);
            }
 
            if (seleccionado == "Listar Huespedes") {
                query = null;
                query = controlador.DBSentencias.listaHues;

                //System.out.println(query);
            }


    }//GEN-LAST:event_cboxListasItemStateChanged
    }
    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaDB().setVisible(true);
            }
        });
    }

    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JComboBox cboxListas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMuestra;
    // End of variables declaration//GEN-END:variables
}
