/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.ConeccionBD;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author peyu
 */
public class ResultadoBusqueda extends javax.swing.JDialog {

    private String query=controlador.DBSentencias.HuesParam;
    
    /**
     * Creates new form ResultadoBusqueda
     */
    //constructor sobrecargado que recibe parametro de busqueda
    public ResultadoBusqueda(javax.swing.JDialog parent, boolean modal,String busqueda) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        //agrego parametro de busqueda al query
        query= query+ "AND nombre LIKE'%" + busqueda +"%' ;"; //Los % hacen que sea posible
                                                              //busquedas parciales  
        System.out.println(query);
        
       int filas =0;
        
        
        try
        {
        
            ResultSetMetaData metaDatos=null;
            int cantiCol=0;
            
            ConeccionBD cone= new ConeccionBD();
            Statement sentencia = cone.conectar.createStatement();
            ResultSet rs= sentencia.executeQuery(query);
            
            DefaultTableModel modelo = new DefaultTableModel();  
              
            modelo = ConeccionBD.ResSet2DTM(rs); //recibe un resultset y devuelve un DefaultTableModel configurado
            
            tblResul.setModel(modelo);
            
            metaDatos = rs.getMetaData();  // Consigo los metadatos
            cantiCol= metaDatos.getColumnCount();    // Consigo la cantidad de columnas                     
            
            
            
            while (rs.next())
               {
                    // Se crea un array que será una de las filas de la tabla.
                    Object [] nuevaFila = new Object[cantiCol]; // Hay cuatro columnas en la tabla

                    // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
                    for (int i=0;i<cantiCol;i++){
                        nuevaFila[i] = rs.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1.
                        
                    }
               
                    // Se añade al modelo la fila completa.
                    modelo.addRow(nuevaFila);                     
               }
            
        }
        
        catch(Exception e){ e.printStackTrace();}
        
        
    }
    
    public ResultadoBusqueda(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResul = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblResul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultadoBusqueda dialog = new ResultadoBusqueda(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResul;
    // End of variables declaration//GEN-END:variables
}
